#!/usr/bin/python
# -*- coding: utf-8 -*-
# Gréoux Research - www.greoux.re


import os
import json

import numpy as np
import matplotlib.pyplot as plt


from datetime import datetime
import u as u


now = datetime.now()
formatted_date = now.strftime("%B %d, %Y %I:%M %p")


needle = '\n\\begin{center} \\small Autogenerated by Integrated Energy Systems Optimiser (IESO) v' + u.ieso_version + ' on ' + str(formatted_date) + ' \\end{center}\n'


tex = ''

tex += '\n\\documentclass[11pt]{article}'
tex += '\n\\usepackage{a4wide}'
tex += '\n\\usepackage{graphicx}'
tex += '\n\\usepackage{caption}'
tex += '\n\\usepackage{subcaption}'
tex += '\n\\usepackage{float}'
tex += '\n\\usepackage{amssymb}'
tex += '\n\\usepackage[dvipsnames]{xcolor}'
tex += '\n\\usepackage{endnotes}'
tex += '\n\\usepackage[T1]{fontenc}'
tex += '\n\\usepackage{newclude}'
tex += '\n\\usepackage{import}'
tex += '\n\\usepackage{pdflscape}'
tex += '\n\\usepackage{hyperref}'
tex += '\n'
tex += '\n\\restylefloat{table}'
tex += '\n\\usepackage{array}'
tex += '\n'
tex += '\n\\renewcommand{\\familydefault}{\\sfdefault}'
tex += '\n'
tex += '\n\\setlength{\\parskip}{0.5em}'
tex += '\n'
tex += '\n\\begin{document}'
tex += '\n'
tex += '\n\\setlength{\\parindent}{0pt}'
tex += '\n'
tex += '\n\\title{Simulation Output Summary}'
tex += '\n\\author{Integrated Energy Systems Optimiser (IESO) v' + u.ieso_version + ' · www.github.com/greoux-research/ieso}'
tex += '\n\\date{' + str(formatted_date) + '}'
tex += '\n'
tex += '\n\\maketitle'
tex += '\n'
tex += '\n'
tex += needle
tex += '\n'
tex += '\n'
tex += '\n\\end{document}'
tex += '\n'


input_summary = False


def init(flag = ''):

    global input_summary

    if flag == 'Input Summary':

        input_summary = True

    readme = 'The context of this folder is generated by by report.py, which transforms IESO\'s IO file into a LaTeX report. Once the LaTex source is generated, compile it using a LaTeX compiler like pdflatex and view the resulting PDF file.'

    try:

        os.system('rd /s /q report') # On Windows
        os.system('rm -rf report') # On Unix-like systems

    except:

        pass

    os.makedirs('report', exist_ok=True)

    with open('report/README.md', 'w') as README_md:

        README_md.write(readme)


def save():

    global input_summary, tex

    tex = tex.replace('[Currency]', '\\$')

    if input_summary:

        tex = tex.replace('Simulation Output Summary', 'Input Summary')

    u.textToFile(tex, 'report/report.tex')


def add_section(titl):

    global tex

    add_tex = '\n'

    add_tex += '\\section*{' + titl + '}'

    add_tex += '\n'

    add_tex += needle

    tex = tex.replace(needle, add_tex)


def add_text(text):

    global tex

    add_tex = '\n'

    add_tex += text

    add_tex += '\n'

    add_tex += needle

    tex = tex.replace(needle, add_tex)


def add_figure(file, caption, label):

    global tex

    add_tex = '\n'

    add_tex += '\n\\begin{figure}[H]'
    add_tex += '\n\\centering'
    add_tex += '\n\\includegraphics[width=1.0\\textwidth]{' + file + '}'
    add_tex += '\n\\caption{' + caption + '}'
    add_tex += '\n\\label{fig:' + label + '}'
    add_tex += '\n\\end{figure}'

    add_tex += '\n'

    add_tex += needle

    tex = tex.replace(needle, add_tex)


def add_list(list, no_spacing=True):

    global tex

    add_tex = '\n'

    add_tex += '\n\\begin{itemize}'

    if no_spacing:

        add_tex += '\n\\setlength{\\itemsep}{0pt}'
        add_tex += '\n\\setlength{\\parskip}{0pt}'
        add_tex += '\n\\setlength{\\parsep}{0pt}'

    for item in list:

        add_tex += '\n\\item ' + str(item)

    add_tex += '\n\\end{itemize}'

    add_tex += '\n'

    add_tex += needle

    tex = tex.replace(needle, add_tex)
